pipeline {
    agent any
    tools {
        gradle 'gradle'
    }
    environment {
        // 환경 변수를 선언하고 초기화
        GITLAB_SOURCE_BRANCH = "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
        GITLAB_TARGET_BRANCH = "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    }
    post {
        success {
            // 빌드가 성공했을 때 GitLab에 성공 상태를 알립니다.
            updateGitlabCommitStatus name: 'build', state: 'success'
        }

        failure {
            // 빌드가 실패했을 때 GitLab에 실패 상태를 알립니다.
            updateGitlabCommitStatus name: 'build', state: 'failed'
        }
    }

    stages {
        stage('Get Merge Request and preBuildMerge') {
            steps {
                cleanWs()
//                 script {
//                     echo "The GitLab source branch is: ${GITLAB_SOURCE_BRANCH}"
//                     echo "The GitLab target branch is: ${GITLAB_TARGET_BRANCH}"
//                     checkout([
//                         $class: 'GitSCM',
//                         branches: [[name: "origin/${GITLAB_SOURCE_BRANCH}"]],
//                         doGenerateSubmoduleConfigurations: false,
//                         extensions: [[$class: 'PreBuildMerge', options: [mergeRemote: 'origin', mergeTarget: "${GITLAB_TARGET_BRANCH}"]]],
//                         submoduleCfg: [],
//                         userRemoteConfigs: [[credentialsId: 'gitlab_access_token', url: 'https://lab.ssafy.com/s10-bigdata-recom-sub2/S10P22A707.git']]
//                     ])
//                 }
                checkout scm
            }
        }

        stage('Run Container') {
            steps {
                dir('exec/docker') {
                    sh 'docker-compose -f docker-compose.yml up -d'
                }
            }
        }

        stage('Setup build environment') {
            steps {
                script {
                        sh 'rm -rf backend/env'
                        sh 'mkdir -p backend/env'
                        sh "chown -R jenkins:jenkins backend/env"
                        sh "chmod -R 755 backend/env"
                }


                withCredentials([file(credentialsId: 'db', variable: 'dbFile')]) {
                    script {
                        sh 'cp $dbFile backend/env/db.env'
                    }
                }


                withCredentials([file(credentialsId: 'test-db', variable: 'testdbFile')]) {
                    script {
                        sh 'cp $testdbFile backend/env/test-db.env'
                    }
                }
                withCredentials([file(credentialsId: 'security', variable: 'securityFile')]) {
                    script {
                        sh 'cp $securityFile backend/env/security.env'
                    }
                }
                sh 'chmod +x ./backend/gradlew'
                sh './backend/gradlew build -p backend'
            }
        }

        stage('Build') {
            steps {
                echo 'Building...'
                 // 빌드 실행
                 dir('backend') {
                    // backend 디렉토리 안에서 빌드 실행
                    sh './gradlew build'
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Test...'
                // 테스트 실행
                dir('backend') {
                    // backend 디렉토리 안에서 빌드 실행
                    sh './gradlew test'
                }
            }
        }
    }
}