pipeline {
    agent any
    tools {
            gradle 'gradle'
        }
    stages {
        stage('Setup build environment') {
            steps {
                echo 'Setting up build environment...'
                sh './backend/gradlew build -p backend'
                sh 'chmod +x ./backend/gradlew'
            }
        }
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building...'
                 // 빌드 실행
                sh './gradlew build'
            }
        }
        stage('Test') {
            steps {
                echo 'Test...'
                // 테스트 실행
                sh './gradlew test'
            }
        }
    }
}