pipeline {
    agent any
    tools {
            gradle 'gradle'
        }

    stages {
        stage('Checkout') {
              steps {
                checkout scm
//                  git branch: './develop',
//                     credentialsId: 'gitlab_access_token',
//                     url: 'https://lab.ssafy.com/s10-bigdata-recom-sub2/S10P22A707'
             }

         }

        stage('Setup build environment') {
            steps {
                script {
                        sh "chown -R jenkins:jenkins backend/env"
                        sh "chmod -R 755 backend/env"
                        sh 'mkdir -p backend/env'
                }
                withCredentials([file(credentialsId: 'db', variable: 'dbFile')]) {
                    script {
                        sh 'cp $dbFile backend/env/db.env'
                    }
                }
                withCredentials([file(credentialsId: 'test-db', variable: 'testdbFile')]) {
                    script {
                        sh 'cp $testdbFile backend/env/test-db.env'
                    }
                }
                echo 'Setting up build environment...'
                sh 'chmod +x ./backend/gradlew'
                sh './backend/gradlew build -p backend'
            }
        }

        stage('Run Container') {
            steps {
                dir('exec/docker') {
                    sh 'docker-compose -f docker-compose.yml up -d'
                }
            }
        }


        stage('Build') {
            steps {
                echo 'Building...'
                 // 빌드 실행
                 dir('backend') {
                    // backend 디렉토리 안에서 빌드 실행
                    sh './gradlew build'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Test...'
                // 테스트 실행
                dir('backend') {
                    // backend 디렉토리 안에서 빌드 실행
                    sh './gradlew test'
                }
            }
        }
    }
}