CREATE DATABASE IF NOT EXISTS tfeo;

CREATE DATABASE IF NOT EXISTS tfeo_test;
CREATE DATABASE IF NOT EXISTS tfeo_temp;

CREATE USER 'tfeo'@'%' IDENTIFIED BY 'tfeo123';

GRANT ALL PRIVILEGES ON `tfeo_test`.* TO 'tfeo'@'%';
GRANT ALL PRIVILEGES ON `tfeo_temp`.* TO 'tfeo'@'%';

FLUSH PRIVILEGES;
